<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [1]:
!pip install pandas
!pip install matplotlib

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.3.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [31]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [3]:
# Write your code here
df.dtypes

ResponseId               int64
MainBranch              object
Age                     object
Employment              object
RemoteWork              object
                        ...
JobSatPoints_11        float64
SurveyLength            object
SurveyEase              object
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object

In [7]:
len(df)

65437

In [8]:
## Write your code here
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(df.isnull().sum())

ResponseId                            0
MainBranch                            0
Age                                   0
Employment                            0
RemoteWork                        10631
Check                                 0
CodingActivities                  10971
EdLevel                            4653
LearnCode                          4949
LearnCodeOnline                   16200
TechDoc                           24540
YearsCode                          5568
YearsCodePro                      13827
DevType                            5992
OrgSize                           17957
PurchaseInfluence                 18031
BuyNewTool                        20256
BuildvsBuy                        22079
TechEndorse                       21769
Country                            6507
Currency                          18753
CompTotal                         31697
LanguageHaveWorkedWith             5692
LanguageWantToWorkWith             9685
LanguageAdmired                   14565
DatabaseHaveWorkedWith            15183
DatabaseWantToWorkWith            22879
DatabaseAdmired                   26880
PlatformHaveWorkedWith            23071
PlatformWantToWorkWith            30905
PlatformAdmired                   34060
WebframeHaveWorkedWith            20276
WebframeWantToWorkWith            26902
WebframeAdmired                   30494
EmbeddedHaveWorkedWith            43223
EmbeddedWantToWorkWith            47837
EmbeddedAdmired                   48704
MiscTechHaveWorkedWith            25994
MiscTechWantToWorkWith            32473
MiscTechAdmired                   35841
ToolsTechHaveWorkedWith           12955
ToolsTechWantToWorkWith           19353
ToolsTechAdmired                  21440
NEWCollabToolsHaveWorkedWith       7845
NEWCollabToolsWantToWorkWith      13350
NEWCollabToolsAdmired             14726
OpSysPersonal use                  7263
OpSysProfessional use             12464
OfficeStackAsyncHaveWorkedWith    17344
OfficeStackAsyncWantToWorkWith    26471
OfficeStackAsyncAdmired           28233
OfficeStackSyncHaveWorkedWith      9892
OfficeStackSyncWantToWorkWith     18726
OfficeStackSyncAdmired            20725
AISearchDevHaveWorkedWith         20984
AISearchDevWantToWorkWith         28736
AISearchDevAdmired                29894
NEWSOSites                         5151
SOVisitFreq                        5901
SOAccount                          5877
SOPartFreq                        20200
SOHow                              6475
SOComm                             6274
AISelect                           4530
AISent                            19564
AIBen                             28543
AIAcc                             28135
AIComplex                         28416
AIToolCurrently Using             30365
AIToolInterested in Using         34746
AIToolNot interested in Using     41023
AINextMuch more integrated        51999
AINextNo change                   52939
AINextMore integrated             41009
AINextLess integrated             63082
AINextMuch less integrated        64289
AIThreat                          20748
AIEthics                          23889
AIChallenges                      27906
TBranch                           20960
ICorPM                            35636
WorkExp                           35779
Knowledge_1                       36773
Knowledge_2                       37416
Knowledge_3                       37342
Knowledge_4                       37407
Knowledge_5                       37557
Knowledge_6                       37573
Knowledge_7                       37659
Knowledge_8                       37679
Knowledge_9                       37802
Frequency_1                       37068
Frequency_2                       37073
Frequency_3                       37727
TimeSearching                     36526
TimeAnswering                     36593
Frustration                       37186
ProfessionalTech                  37673
ProfessionalCloud                 36946
ProfessionalQuestion              36630
Industry                          36579
JobSatPoints_1                    36113
JobSatPoints_4                    36044
JobSatPoints_5                    36026
JobSatPoints_6                    35987
JobSatPoints_7                    35989
JobSatPoints_8                    35981
JobSatPoints_9                    35981
JobSatPoints_10                   35987
JobSatPoints_11                   35992
SurveyLength                       9255
SurveyEase                         9199
ConvertedCompYearly               42002
JobSat                            36311
dtype: int64

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [6]:
# Write your code here
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [32]:
# Write your code here
df.Country = df.Country.str.lower() 

country_dict = {'united states of america': 'usa', 
                'united kingdom of great britain and northern ireland' : 'uk', 
                'iran, islamic republic of...' : 'iran',
                'republic of north macedonia' : 'north macedonia',
                'russian federation' : 'russia', 
                'united republic of tanzania' : 'tanzania', 
                'venezuela, bolivarian republic of...' : 'venezuela',
                'republic of moldova' : 'moldova', 
                'united arab emirates' : 'uae', 
                'hong kong (s.a.r.)' : 'hong kong',   
                "lao people's democratic republic" : 'laos', 
                'democratic republic of the congo' : 'dr congo',
                'syrian arab republic': 'syria', 
                "côte d'ivoire" : 'cdi', 
                "democratic people's republic of korea" : 'north korea',
                'congo, republic of the...' : 'congo',  
                'libyan arab jamahiriya' : 'libya', 
                'brunei darussalam' : 'brunei',  
                'micronesia, federated states of...' : 'micronesia'}  
                

df.loc[df.Country == 'viet nam', 'Country'] = 'vietnam'
df['Country'] = df['Country'].replace(country_dict)
df.Country.unique()

array(['usa', 'uk', 'canada', 'norway', 'uzbekistan', 'serbia', 'poland',
       'philippines', 'bulgaria', 'switzerland', 'india', 'germany',
       'ireland', 'italy', 'ukraine', 'australia', 'brazil', 'japan',
       'austria', 'iran', 'france', 'saudi arabia', 'romania', 'turkey',
       'nepal', 'algeria', 'sweden', 'netherlands', 'croatia', 'pakistan',
       'czech republic', 'north macedonia', 'finland', 'slovakia',
       'russia', 'greece', 'israel', 'belgium', 'mexico', 'tanzania',
       'hungary', 'argentina', 'portugal', 'sri lanka', 'latvia', 'china',
       'singapore', 'lebanon', 'spain', 'south africa', 'lithuania',
       'vietnam', 'dominican republic', 'indonesia', 'kosovo', 'morocco',
       'taiwan', 'georgia', 'san marino', 'tunisia', 'bangladesh',
       'nigeria', 'liechtenstein', 'denmark', 'ecuador', 'malaysia',
       'albania', 'azerbaijan', 'chile', 'ghana', 'peru', 'bolivia',
       'egypt', 'luxembourg', 'montenegro', 'cyprus', 'paraguay',
       'kazakhstan', 'slovenia', 'jordan', 'venezuela', 'costa rica',
       'jamaica', 'thailand', 'nicaragua', 'myanmar', 'republic of korea',
       'rwanda', 'bosnia and herzegovina', 'benin', 'el salvador',
       'zimbabwe', 'afghanistan', 'estonia', 'malta', 'uruguay',
       'belarus', 'colombia', 'moldova', 'isle of man', 'nomadic',
       'new zealand', 'palestine', 'armenia', 'uae', 'maldives',
       'ethiopia', 'fiji', 'guatemala', 'uganda', 'turkmenistan',
       'mauritius', 'kenya', 'cuba', 'gabon', 'bahamas', 'south korea',
       'iceland', 'honduras', 'hong kong', 'laos', 'mongolia', 'cambodia',
       'madagascar', 'angola', 'dr congo', 'syria', 'iraq', 'namibia',
       'senegal', 'kyrgyzstan', 'zambia', 'swaziland', 'cdi', 'kuwait',
       'tajikistan', 'burundi', 'trinidad and tobago', 'mauritania',
       'sierra leone', 'panama', 'somalia', 'north korea', 'dominica',
       'guyana', 'togo', 'oman', 'barbados', 'andorra', 'qatar', 'sudan',
       'cameroon', 'papua new guinea', 'bahrain', 'yemen', 'malawi',
       'burkina faso', 'congo', 'botswana', 'guinea-bissau', 'mozambique',
       'central african republic', 'equatorial guinea', 'suriname',
       'belize', 'libya', 'cape verde', 'brunei', 'bhutan', 'guinea',
       'niger', 'antigua and barbuda', 'mali', 'samoa', 'lesotho',
       'saint kitts and nevis', 'monaco', 'micronesia', 'haiti', nan,
       'nauru', 'liberia', 'chad', 'djibouti', 'solomon islands'],
      dtype=object)

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [38]:
## Write your code here
# Country done above 
edlevel_dict = {'Primary/elementary school' : 'Primary', 
                'Bachelor’s degree (B.A., B.S., B.Eng., etc.)' : 'Bachelor',
               'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)' : 'Masters', 
               'Some college/university study without earning a degree' : 'CourseUnits', 
               'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)' : 'GED', 
               'Professional degree (JD, MD, Ph.D, Ed.D, etc.)' : 'Professional',
                'Associate degree (A.A., A.S., etc.)' : 'Associate', 
                'Something else' : 'Other'}
                
df['EdLevel'] = df['EdLevel'].replace(edlevel_dict)
df['EdLevel'].fillna('NA', inplace=True)
df.EdLevel.unique()

/tmp/ipykernel_1818/2414193309.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['EdLevel'].fillna('NA', inplace=True)

array(['Primary', 'Bachelor', 'Masters', 'CourseUnits', 'GED',
       'Professional', 'Associate', 'Other', 'NA'], dtype=object)

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [39]:
## Write your code here
df_encoded = pd.get_dummies(df, columns=['Employment'])
df_encoded

,ResponseId,MainBranch,Age,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,"Employment_Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time","Employment_Student, full-time;Not employed, but looking for work;Retired","Employment_Student, full-time;Not employed, but looking for work;Student, part-time","Employment_Student, full-time;Retired","Employment_Student, full-time;Student, part-time","Employment_Student, full-time;Student, part-time;Employed, part-time","Employment_Student, full-time;Student, part-time;Retired","Employment_Student, part-time","Employment_Student, part-time;Employed, part-time","Employment_Student, part-time;Retired"
0,1,I am a developer by profession,Under 18 years old,Remote,Apples,Hobby,Primary,Books / Physical media,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
1,2,I am a developer by profession,35-44 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,Bachelor,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
2,3,I am a developer by profession,45-54 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,Masters,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
3,4,I am learning to code,18-24 years old,NaN,Apples,NaN,CourseUnits,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,False,False,False,False,False,False,False,False,False,False
4,5,I am a developer by profession,18-24 years old,NaN,Apples,NaN,GED,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,Remote,Apples,Hobby;School or academic work,Bachelor,"On the job training;School (i.e., University, ...",NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
65433,65434,I am a developer by profession,25-34 years old,Remote,Apples,Hobby;Contribute to open-source projects,NA,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
65434,65435,I am a developer by profession,25-34 years old,In-person,Apples,Hobby,Bachelor,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,API document(s) and/or SDK document(s);AI-powe...,...,False,False,False,False,False,False,False,False,False,False
65435,65436,I am a developer by profession,18-24 years old,"Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,GED,On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
65436,65437,I code primarily as a hobby,18-24 years old,NaN,Apples,NaN,NA,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [40]:
## Write your code here
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    print(df.isnull().sum())

ResponseId                            0
MainBranch                            0
Age                                   0
Employment                            0
RemoteWork                        10631
Check                                 0
CodingActivities                  10971
EdLevel                               0
LearnCode                          4949
LearnCodeOnline                   16200
TechDoc                           24540
YearsCode                          5568
YearsCodePro                      13827
DevType                            5992
OrgSize                           17957
PurchaseInfluence                 18031
BuyNewTool                        20256
BuildvsBuy                        22079
TechEndorse                       21769
Country                            6507
Currency                          18753
CompTotal                         31697
LanguageHaveWorkedWith             5692
LanguageWantToWorkWith             9685
LanguageAdmired                   14565
DatabaseHaveWorkedWith            15183
DatabaseWantToWorkWith            22879
DatabaseAdmired                   26880
PlatformHaveWorkedWith            23071
PlatformWantToWorkWith            30905
PlatformAdmired                   34060
WebframeHaveWorkedWith            20276
WebframeWantToWorkWith            26902
WebframeAdmired                   30494
EmbeddedHaveWorkedWith            43223
EmbeddedWantToWorkWith            47837
EmbeddedAdmired                   48704
MiscTechHaveWorkedWith            25994
MiscTechWantToWorkWith            32473
MiscTechAdmired                   35841
ToolsTechHaveWorkedWith           12955
ToolsTechWantToWorkWith           19353
ToolsTechAdmired                  21440
NEWCollabToolsHaveWorkedWith       7845
NEWCollabToolsWantToWorkWith      13350
NEWCollabToolsAdmired             14726
OpSysPersonal use                  7263
OpSysProfessional use             12464
OfficeStackAsyncHaveWorkedWith    17344
OfficeStackAsyncWantToWorkWith    26471
OfficeStackAsyncAdmired           28233
OfficeStackSyncHaveWorkedWith      9892
OfficeStackSyncWantToWorkWith     18726
OfficeStackSyncAdmired            20725
AISearchDevHaveWorkedWith         20984
AISearchDevWantToWorkWith         28736
AISearchDevAdmired                29894
NEWSOSites                         5151
SOVisitFreq                        5901
SOAccount                          5877
SOPartFreq                        20200
SOHow                              6475
SOComm                             6274
AISelect                           4530
AISent                            19564
AIBen                             28543
AIAcc                             28135
AIComplex                         28416
AIToolCurrently Using             30365
AIToolInterested in Using         34746
AIToolNot interested in Using     41023
AINextMuch more integrated        51999
AINextNo change                   52939
AINextMore integrated             41009
AINextLess integrated             63082
AINextMuch less integrated        64289
AIThreat                          20748
AIEthics                          23889
AIChallenges                      27906
TBranch                           20960
ICorPM                            35636
WorkExp                           35779
Knowledge_1                       36773
Knowledge_2                       37416
Knowledge_3                       37342
Knowledge_4                       37407
Knowledge_5                       37557
Knowledge_6                       37573
Knowledge_7                       37659
Knowledge_8                       37679
Knowledge_9                       37802
Frequency_1                       37068
Frequency_2                       37073
Frequency_3                       37727
TimeSearching                     36526
TimeAnswering                     36593
Frustration                       37186
ProfessionalTech                  37673
ProfessionalCloud                 36946
ProfessionalQuestion              36630
Industry                          36579
JobSatPoints_1                    36113
JobSatPoints_4                    36044
JobSatPoints_5                    36026
JobSatPoints_6                    35987
JobSatPoints_7                    35989
JobSatPoints_8                    35981
JobSatPoints_9                    35981
JobSatPoints_10                   35987
JobSatPoints_11                   35992
SurveyLength                       9255
SurveyEase                         9199
ConvertedCompYearly               42002
JobSat                            36311
dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [46]:
## Write your code here 
numerical_cols = df.select_dtypes(include='number').columns.tolist()
numerical_cols.remove('ResponseId') 
numerical_cols

['CompTotal',
 'WorkExp',
 'JobSatPoints_1',
 'JobSatPoints_4',
 'JobSatPoints_5',
 'JobSatPoints_6',
 'JobSatPoints_7',
 'JobSatPoints_8',
 'JobSatPoints_9',
 'JobSatPoints_10',
 'JobSatPoints_11',
 'ConvertedCompYearly',
 'JobSat']

In [49]:
for c in numerical_cols: 
    df[c] = df[c].fillna(df[c].mean())
    print(c, df[c].isna().sum())

CompTotal 0
WorkExp 0
JobSatPoints_1 0
JobSatPoints_4 0
JobSatPoints_5 0
JobSatPoints_6 0
JobSatPoints_7 0
JobSatPoints_8 0
JobSatPoints_9 0
JobSatPoints_10 0
JobSatPoints_11 0
ConvertedCompYearly 0
JobSat 0

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [56]:
## Write your code here
object_columns_df = df.select_dtypes(include=['object'])
cat_cols = object_columns_df.columns
for c in cat_cols: 
    df[c] = df[c].fillna(df[c].mode()[0])

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [57]:
## Write your code here
# Find the minimum and maximum values in 'ConvertedCompYearly'
min_value = float(df['ConvertedCompYearly'].min())
max_value = float(df['ConvertedCompYearly'].max())

# Apply Min-Max normalization to 'ConvertedCompYearly'
df['ConvertedCompYearly_MinMax'] = (df['ConvertedCompYearly'].astype(float) - min_value) / (max_value - min_value)

/tmp/ipykernel_1818/2466946829.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ConvertedCompYearly_MinMax'] = (df['ConvertedCompYearly'].astype(float) - min_value) / (max_value - min_value)

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [59]:
## Write your code here
import numpy as np 
df['Log_ConvertedCompYearly'] = np.log(df['ConvertedCompYearly'] + 1)
df

/tmp/ipykernel_1818/1130372447.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['Log_ConvertedCompYearly'] = np.log(df['ConvertedCompYearly'] + 1)

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat,ConvertedCompYearly_MinMax,Log_ConvertedCompYearly
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary,Books / Physical media,Technical documentation;Blogs;Written Tutorial...,...,20.278165,16.169432,10.955713,9.953948,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,Bachelor,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.000000,0.000000,0.000000,0.000000,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,Masters,Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,20.278165,16.169432,10.955713,9.953948,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918
3,4,I am learning to code,18-24 years old,"Student, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,CourseUnits,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,20.278165,16.169432,10.955713,9.953948,Too long,Easy,86155.287263,6.935041,0.0053,11.363918
4,5,I am a developer by profession,18-24 years old,"Student, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,GED,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,20.278165,16.169432,10.955713,9.953948,Too short,Easy,86155.287263,6.935041,0.0053,11.363918
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,65433,I am a developer by profession,18-24 years old,"Employed, full-time",Remote,Apples,Hobby;School or academic work,Bachelor,"On the job training;School (i.e., University, ...",Technical documentation;Blogs;Written Tutorial...,...,20.278165,16.169432,10.955713,9.953948,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918
65433,65434,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,NA,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,20.278165,16.169432,10.955713,9.953948,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918
65434,65435,I am a developer by profession,25-34 years old,"Employed, full-time",In-person,Apples,Hobby,Bachelor,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Stack Overflow;Social ...,...,20.278165,16.169432,10.955713,9.953948,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918
65435,65436,I am a developer by profession,18-24 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,GED,On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,0.000000,0.000000,0.000000,0.000000,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918
65436,65437,I code primarily as a hobby,18-24 years old,"Student, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,NA,"Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,20.278165,16.169432,10.955713,9.953948,Appropriate in length,Easy,86155.287263,6.935041,0.0053,11.363918

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [66]:
## Write your code here
exp_dict = {'Less than 1 year' : '1', 'More than 50 years' : '50'}
           
df['ExperienceLevel'] = df['YearsCodePro'].replace(exp_dict)
df['ExperienceLevel'] = df['ExperienceLevel'].astype(int)
df.ExperienceLevel.unique()

array([ 2, 17, 27,  7, 11, 25, 12, 10,  3,  1, 18, 37, 15, 20,  6, 16,  8,
       14,  4, 45, 24, 29,  5, 30, 26,  9, 33, 13, 35, 23, 22, 31, 19, 21,
       28, 34, 32, 40, 50, 39, 44, 42, 41, 36, 38, 43, 47, 48, 46, 49])

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.